version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
  reviewers:
  - dianw
  - diaxz
  - vickyfaizal
  ignore:
  - dependency-name: com.icegreen:greenmail
    versions:
    - 1.6.1
    - 1.6.2
  - dependency-name: org.webjars:bootstrap
    versions:
    - 4.6.0
  - dependency-name: pl.project13.maven:git-commit-id-plugin
    versions:
    - 4.0.3
