info:
  app:
    encoding: "@project.build.sourceEncoding@"
    artifact:
      artifactId: "@project.artifactId@"
      groupId: "@project.groupId@"
      version: "@project.version@"
    java:
      source: "@java.version@"
      target: "@java.version@"
logging:
  level:
    org.codenergic.theskeleton: DEBUG
management:
  info:
    git:
      mode: full
s3:
  client:
    endpoint: http://localhost:8082
    access-key: supersecret
    secret-key: supersecret123
    buckets:
      - name: profile-pictures
      - name: galleries
spring:
  datasource:
    url: jdbc:h2:~/.theskeleton-0.13.0;AUTO_SERVER=TRUE
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /manage/database
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      javax:
        persistence:
          sharedCache:
            mode: DISABLE_SELECTIVE
      hibernate:
        cache:
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
          use_second_level_cache: true
        jdbc:
          time_zone: UTC
  mail:
    host: localhost
    port: 1025
    username:
    password:
    properties:
      sender: theskeleton@codenergic.org
      senderAlias: TheSkeleton
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
            required: false
  security:
    filter:
      order: 3
    jwt:
      signing-key: VNcRqdXpj9nHZQqtmf5l
  social:
    facebook:
      app-id: 897090537127510
      app-secret: 38fc52cda45ce507ae37df2d3105ebbf
    google:
      app-id: 1031466054059-efbl8kv8luoegprdsdubkq4kba3qvcuo.apps.googleusercontent.com
      app-secret: pTj_xuAmNSmx0nOhTTsMpCZN
  thymeleaf:
    cache: false
email:
    baseurl: http://localhost:8080
